"""yanzheng

Revision ID: 268fea3d5966
Revises: 6c068b4df353
Create Date: 2018-01-09 12:28:45.724236

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '268fea3d5966'
down_revision = '6c068b4df353'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('confirmed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'confirmed')
    # ### end Alembic commands ###
